version: "3.8"
services:
  mongodb:
    platform: linux/amd64
    image: mongo:latest
    ports:
      - "27017:27017"
  demo-service:
    build: .
    platform: linux/amd64
    ports:
      - "8082:8082"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb